name: Trigger auto deployment for tax-talk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tax-talk-AutoDeployTrigger-069db4a4-1743-4a26-95a1-6a5ef82e2996.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TAXTALK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TAXTALK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TAXTALK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: taxtalk-b5a6hqbaare6e5e6.azurecr.io
          registryUsername: ${{ secrets.TAXTALK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TAXTALK_REGISTRY_PASSWORD }}
          containerAppName: tax-talk
          resourceGroup: tax-talk-rg
          imageToBuild: taxtalk-b5a6hqbaare6e5e6.azurecr.io/tax-talk:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


